### ISSUE TITLE
[ISSUE] - "Accept only quest(s) from route" Auto-Accepts All Quests

### ISSUE THREAD

**Issue by ValokAsura** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#327]
### Description

Expectation: When I have all options in "General Automation" un-checked, I want to be forced to manually accept quests from NPCs. I would expect this to be the case with or without a route loaded.

What happens: When either "Accept the quest(s)" or "Accept only quest(s) from route" is checked, the addon will auto-accept any quest from any NPC I talk to when I don't have a route loaded. I tested with several NPCs in Stormwind and one in Dalaran. Both have to be disabled in order to allow me to manually accept a quest.

APR v.4.2.3 downloaded via CurseForge App.

### World of Warcraft Flavor

Retail (Default)

### APR Status

{{"Class","DEATHKNIGHT"},{"Continent","Eastern Kingdoms"},{"Time & Date","Fri Aug 23 07:40:28 2024"},{"Language","enUS"},{"Name","Deddish"},{"Realm","Bronzebeard"},{"World Coordinates","605.90, -8847.90"},{"Level","26"},{"AddOn Version","v4.2.3"},{"Faction","Alliance"},{"Coordinates","64.29, 73.56"},{"Client Build","56288"},{"Client Version","11.0.2"},{"Step","No active route"},{"Route","No active route"},{"Zone","Stormwind City"}}

### Tested with only APR

- [X] Yes
- [ ] No

### Lua Error

No errors. Tested by having APR as the only addon, then a test with only APR, BugSack, and BugGrabber loaded.

### Reproduction Steps

1. Open APR options and check "Accept only quest(s) from route" from General Automation.
2. Ensure no route is loaded.
3. Talk to an NPC that offers a quest. The quest will be automatically accepted.
5. Abandon the quest.
6. Open APR options and un-check "Accept only quest(s) from route" from General Automation.
7. Talk to the same NPC that offers a quest. The quest will not be automatically accepted.

### Any additional information?

I think it's a simple case of both checkboxes accidentally setting the same option.

Thank you for your time, and great addon!

**Comment by Neogeekmo** [comment]
This is not a bug, but normal behavior. If you don't have a route selected but have auto-accept enabled in your options, it will pick up all quests by default.

It's true, the "Accept only quest(s) from route" option might make you think it won't pick up any quests if you don't have a route.
But the idea was to keep the quest pickup functionality even when there's no route selected.

I'll consider either adding an indication in a tooltip or changing it so that it doesn't pick up every quests with the second option enable

**Comment by NightofStarrs** [comment]
Hi @ValokAsura

This was a bit of an oversight to how our automation works, previously we only allowed a Yes/No approach to accepting quests, which inherently picked up all quests and flooded your quest log until we cleared it towards the end of that zone's route. Because of this, and some people requesting a better option to this - we enabled it to be either 'Accept All' or 'Accept Quests Only in Route' which accepted just the quests in the route from that NPC at that time. What the issue that you're mentioning is that you don't have a route enabled, and therefore there shouldn't be a pool of quests to pull from that route to accept. 

Example:

I am on route 1 - TWW, I have Auto Accept enabled - it accepts ALL quests from the NPC even though only 1 out of the 2 given are in the route.
I am on the same route, but I have it checked to instead only accept quests in the route, so the 1 quest I need is picked up but the second one is ignored.

What we didn't realize though, is that the second option to only accept quests in route was globally accepting all quests when not in a route. This was an oversight in the logic when it was initially applied, as it just looked to see if the step WAS current in the route in question.

Sorry for any issues this had caused, but the logic was never implied with AAP or APR to work 'off route'.

**Comment by NightofStarrs** [comment]
To add, this has been fixed and will be applied in the next release coming out momentarily with bug/route fixes from TWW.

**Comment by ValokAsura** [comment]
I appreciate all of the feedback and explanations! Perhaps my defining it as a bug was inappropriate. Calling it just strange/unexpected behavior would have sufficed :) I wanted to check Discord before I created an issue but I couldn't find a valid invite link.

And it didn't cause any real problems, just a bit of confusion for me and time spent searching all of my addons for something that was possibly accepting quests. I have Leatrix Plus and ElvUI/WindTools installed and so it was a little bit of back and forth/disabled to make sure they didn't have their versions of "Accept Every Quest" enabled.

Thanks again!

**Comment by Neogeekmo** [comment]
@ValokAsura  
it's weird about Discord, I just checked, and the links are correct on all platforms (GitHub, CurseForge, Wago, etc.)

**Comment by ValokAsura** [comment]
@Neogeekmo 
I just took another peek and they don't say Invalid Invite anymore, but they still don't work for me. It looks like a proper invitation, but this is what I get when I try to join. Perhaps I was pre-banned :)

I was hoping to learn if I would be capable of contributing by creating routes for rarely-visited zones that might be at the bottom of the priority list, assuming they exist in the first place :)

![Discord](https://github.com/user-attachments/assets/f08b6079-6ce2-4d43-bf12-5998155983ce)

**Comment by NightofStarrs** [comment]
@ValokAsura can I get your discord username/ID?

**Comment by Neogeekmo** [comment]
try this invit 
https://discord.gg/5ZEbenge79

**Comment by ValokAsura** [comment]
@NightofStarrs  VoiD7859

@Neogeekmo No luck, but thank you for the link!
![Discord 2](https://github.com/user-attachments/assets/1b18d84f-7a71-494c-8b65-339c450722e2)

**Comment by NightofStarrs** [comment]
@ValokAsura I don't see you as being banned or anything, so something is weird with your discord. The original invite by Rycia [discord.gg/YgcdybKdWX](https://discord.com/invite/YgcdybKdWX) and the one Neo just gave [discord.gg/5ZEbenge79](https://discord.com/invite/5ZEbenge79) are both active and set to not expire. So, something is definitely weird I think with your Discord.

**Comment by ValokAsura** [comment]
Thank you both for your assistance with Discord! I'm glad it's just something on my end, and I'll look into it.
